Simplify HTML by combining all "simple" tiles into one template
resoai/TileBoard pull request #412
Opened 2020-08-31 12:25 UTC by akloeckner

When setting up popups, I came across the fact that many many tiles actually had the very same content. I fixed that up into one tile template. Basically not much changes, but the code gets much smaller and simpler. 

In this course, I also removed one superfluous function, because the existent and more generic function `itemField` could be used instead.

Things that do change:
* all simple tiles have `customHtml` option now.
* the customHtml option additionally accepts templates now.

2020-08-31 13:07 UTC, rchl requested changes

2020-08-31 13:07 UTC, rchl commented on scripts/controllers/main.js
> -      return item.customHtml;
Going through `parseString` rather than just using the string verbatim like before can break existing use cases. I think we should keep previous behavior. At least by default.

2020-08-31 13:07 UTC, rchl commented on README.md
>    icon: 'mdi-phone'
Let's add the missing comma here as otherwise highlighting breaks in my editor at least.

2020-09-02 21:25 UTC, akloeckner commented on scripts/controllers/main.js
> -      return item.customHtml;
I thought about that, but I couldn't really think of a (probable) use case, which would break. It would only break in the rare case that someone uses a `@` (or `&`) followed by a verbatim HA attribute (or state) name, even including the `.`s. Why would someone want to have that in their custom HTML? 

The most probable would be `@state`. But even that is a string I'd judge uncommon to appear in a tile. 

On the other hand, I even found it counter-intuitive that in all other places, template can be used interchangeably with anonymous functions. But not here. I'd assume, it is even an oversight that it wasn't possible before. 

That's why I suggest to unify this. (Here and in most other places we can find, I'd dare say.)

But maybe you have reasonable use cases, I didn't think of. Or @resoai can recall the reason, this part should not accept templates? (The code was introduced in #318, just a month ago.)

Another aspect to keep in mind is that probably we cannot always maintain 100% backwards compatibility, if we want to improve things beyond a certain level. I'd judge consistency the higher value. If you keep compatibility up as a core value for the project, though, I'll certainly revert this change.

2020-09-02 21:30 UTC, akloeckner commented on README.md
>    icon: 'mdi-phone'
I already wondered, why the readme looked strange in that place... done.

2020-09-03 11:21 UTC, resoai commented on scripts/controllers/main.js
> -      return item.customHtml;
It does indeed look like an oversight to me. New tiles have been added quickly, to be honest I never expected it to grow over 5 since I was planning for it to be used solely for my dashboard 😄

2020-09-03 18:56 UTC, akloeckner commented on scripts/controllers/main.js
> -      return item.customHtml;
:-) Isn't it amazing how fast good ideas are picked up?

2020-09-03 23:21 UTC, akloeckner commented on scripts/controllers/main.js
> -      return item.customHtml;
Another option how to handle incompatible CONFIG changes would be to show warnings for a while: https://github.com/akloeckner/TileBoard/commit/4ab21fc509200d35cf535aeb92b05c296d1f439d. After some time we could get rid of those warnings and *really* clean up. But code will become messy with those warnings...

2020-09-04 09:35 UTC, rchl commented on scripts/controllers/main.js
> -      return item.customHtml;
Let's keep it simple and just hope nothing breaks.

2020-09-04 09:37 UTC, merged