refactor: move default actions to TILE_DEFAULTS
resoai/TileBoard pull request #522
Opened 2020-11-09 21:50 UTC by akloeckner

also introduce the option to disable actions by setting `action: false` or `secondaryAction: false`
also show "clickable" tick not for fixed tile types, but for tiles with `action` defined

2020-11-10 21:06 UTC, rchl commented on scripts/controllers/main.js
> +         return null;
I think just `return` would be more correct. Returning `null` for `ng-click` seems like has no special meaning so `undefined` would work just fine also.

2020-11-10 21:15 UTC, rchl requested changes

2020-11-10 21:15 UTC, rchl commented on scripts/globals/constants.js
> +         return this.$scope.openPopup(item, entity);
This one also took the third argument `item.popup` before.

2020-11-10 22:45 UTC, akloeckner commented on scripts/globals/constants.js
> +         return this.$scope.openPopup(item, entity);
Yes. In fact, that was redundant, as the `openPopup` defaults to `item.popup` itself anyway. I dropped when I was trying to find a simpler syntax like
```
action: $scope.openPopup,
```
But I failed to find one. If you can think of one, let me know, please.

Until then, I'll re-introduce the third argument for clarity. Despite its redundancy.

2020-11-11 08:29 UTC, merged

2020-11-11 08:29 UTC, rchl commented
Thanks.