Localized/Custom Weather states
resoai/TileBoard pull request #661
Opened 2021-02-25 18:16 UTC by mikyjazz

- Added in configuration a dictionary to define human readable form of Weather states
- Used 'state' in HEADER.WEATHER if Summary is not defined
- Split Temperature/humidity line in WEATHER tile if tilesize < 140 px
- some little changes in main.CSS

2021-02-25 20:33 UTC, rchl requested changes

2021-02-25 20:33 UTC, rchl commented on scripts/controllers/main.js
> +            }
`typeof null` is also `object` so it's safer to also check that the value is truthy.

Also, please no abbreviated variable names. We can use `state` here.

2021-02-25 20:33 UTC, rchl commented on scripts/directives/tile.html
> +         <div class="weather-line -items" ng-if="(tileSize(page) >= 140)">
This is not a great size check because the tile can have width/height defined to 2 for example.

You could rename `tileSize` to `effectiveTileSize`, for example, then pass the `item` to it also and compute the size including the width/height.

Something like:

```
const tileSize = page.tileSize || CONFIG.tileSize;
return {
  height: (item.height || 1) * tileSize,
  width: (item.width || 1) * tileSize,
}
```

2021-02-25 20:35 UTC, rchl commented on scripts/directives/tile.html
> +         <div class="weather-line -items" ng-if="(tileSize(page) >= 140)">
BTW. No need for redundant parenthesis also :)

2021-02-25 22:52 UTC, mikyjazz commented on scripts/directives/tile.html
> +         <div class="weather-line -items" ng-if="(tileSize(page) >= 140)">
Done, I had forgotten the mechanism for defining the size of the tiles

2021-02-25 23:01 UTC, rchl approved these changes
Thanks.

2021-02-25 23:01 UTC, rchl commented
Will merge tomorrow in case someone else has some comments.

2021-02-25 23:02 UTC, mikyjazz commented
fine, have you read my comment about HA histoyr changes?

2021-03-01 10:54 UTC, mikyjazz commented
Ready new improvement! (After this merge ;) )
[image: grid_tiles.png]

Il giorno ven 26 feb 2021 alle ore 00:01 Rafał Chłodnicki <
notifications@github.com> ha scritto:

> Will merge tomorrow in case someone else has some comments.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/resoai/TileBoard/pull/661#issuecomment-786285632>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJGFTUJQWYSBUYW5IJ6JYXDTA3JGHANCNFSM4YG7R7AQ>
> .
>

2021-03-01 11:02 UTC, merged

2021-03-01 11:02 UTC, rchl commented
Sorry for the delay. :)

2021-03-01 11:54 UTC, mikyjazz commented
no problem ;) have you seen multi-row layout?

Il giorno lun 1 mar 2021 alle ore 12:02 Rafał Chłodnicki <
notifications@github.com> ha scritto:

> Sorry for the delay. :)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/resoai/TileBoard/pull/661#issuecomment-787860352>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJGFTUMYV3OMECUWLEGPJHDTBNX4NANCNFSM4YG7R7AQ>
> .
>

2021-03-01 11:57 UTC, rchl commented
If you mean the image attachment then no because it doesn't show up here on github

2021-03-01 12:00 UTC, mikyjazz commented
ah ok, want you share your email address? (btw i asked you also for contact
on linkedin)

Il giorno lun 1 mar 2021 alle ore 12:58 Rafał Chłodnicki <
notifications@github.com> ha scritto:

> If you mean the image attachment then no because it doesn't show up here
> on github
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/resoai/TileBoard/pull/661#issuecomment-787893303>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJGFTUOFXLNV6BY3FNG4A73TBN6NFANCNFSM4YG7R7AQ>
> .
>

2021-03-01 12:02 UTC, rchl commented
Maybe post that in https://github.com/resoai/TileBoard/issues/638 ?

Github allows image attachment. You might just need to wait with posting the comment until it's fully uploaded.

2021-03-01 12:07 UTC, mikyjazz commented
Yes, I done by myself...
I sent you an image as attachment to reply at previous email lkie this

Il giorno lun 1 mar 2021 alle ore 13:02 Rafał Chłodnicki <
notifications@github.com> ha scritto:

> Maybe post that in #638 <https://github.com/resoai/TileBoard/issues/638> ?
>
> Github allows image attachment. You might just need to wait with posting
> the comment until it's fully uploaded.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/resoai/TileBoard/pull/661#issuecomment-787896347>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AJGFTUJ73Y3HLC4IKLF5X3TTBN663ANCNFSM4YG7R7AQ>
> .
>

2021-03-01 12:20 UTC, mikyjazz commented
![grid_tiles](https://user-images.githubusercontent.com/38558161/109496349-d4dc0380-7a90-11eb-894b-3ab5e24fdfb5.png)
Now I understand how photo attachment works!