Localized climate options
resoai/TileBoard pull request #667
Opened 2021-03-13 21:52 UTC by mikyjazz

- localized/customized lookup for climate options
- icon lookup for climate options
- localized translation for mediaplayer "Source" label

2021-03-14 17:38 UTC, rchl requested changes

2021-03-14 17:38 UTC, rchl commented on config.example.js
> +                     id: "climate.000000000",
Can a value like `{attributes: {current_temperature: 11}` here instead so that there is no popup about missing entity?

2021-03-14 17:38 UTC, rchl commented on scripts/controllers/main.js
> +      const _option = $scope.reverseLookupClimateOption(item, entity, option);
Having both `option` and `_option` variables don't make thing very clear or readable.

In this maybe it can be called `climateMode`.

2021-03-14 17:38 UTC, rchl commented on scripts/directives/tile.html
> +               <span ng-bind="(getWeatherField('windSpeed', item, entity) | number:0)"></span><!--
Should not remove `&nbsp;`

2021-03-14 17:38 UTC, rchl commented on scripts/directives/tile.html
> +               <span ng-bind="(getWeatherField('windSpeed', item, entity) | number:0)"></span><!--
Should not remove `&nbsp;`

2021-03-14 17:38 UTC, rchl commented on scripts/directives/tile.html
> +               <span ng-bind="(getWeatherField('pressure', item, entity) | number:0)"></span><!--
Should not remove `&nbsp;`

2021-03-14 17:38 UTC, rchl commented on scripts/directives/tile.html
> +                     <span ng-bind="entity.attributes.source || item.textSource || 'Source'"></span>
Wouldn't it be better if `item.textSource` overrode everything else if set?

But if it's meant as a fallback when the attribute is missing then I'd suggest calling it `sourceFallbackText` instead.

2021-03-14 17:38 UTC, rchl commented on scripts/directives/tile.html
> +            <i class="item-climate--icon mdi" ng-class="entityIcon(item, entity)"></i>
there is a lot of trailing spaces here

2021-03-14 17:38 UTC, rchl commented on scripts/controllers/main.js
> +         }
I don't have a real entity to test so maybe I'm missing something but I don't understand the point of creating this mapping. It assigns the same value to both the object's key and value so then both the `lookupClimateOption` and `reverseLookupClimateOption` seem to be doing the same thing in practice.

2021-03-14 17:43 UTC, mikyjazz commented on scripts/controllers/main.js
> +      const _option = $scope.reverseLookupClimateOption(item, entity, option);
really is looked-up option... luOption? :)

2021-03-14 17:45 UTC, mikyjazz commented on scripts/directives/tile.html
> +               <span ng-bind="(getWeatherField('windSpeed', item, entity) | number:0)"></span><!--
code before your modification in other branch, for.your,eyes,only :)

2021-03-14 17:45 UTC, mikyjazz commented on scripts/directives/tile.html
> +               <span ng-bind="(getWeatherField('windSpeed', item, entity) | number:0)"></span><!--
idem

2021-03-14 17:45 UTC, mikyjazz commented on scripts/directives/tile.html
> +               <span ng-bind="(getWeatherField('pressure', item, entity) | number:0)"></span><!--
...

2021-03-14 17:46 UTC, mikyjazz commented on scripts/directives/tile.html
> +            <i class="item-climate--icon mdi" ng-class="entityIcon(item, entity)"></i>
adjust spaces as you feel... I don't pay attention...

2021-03-14 17:47 UTC, mikyjazz commented on scripts/directives/tile.html
> +                     <span ng-bind="entity.attributes.source || item.textSource || 'Source'"></span>
maybe better change order like:
item.textSource || entity.attributes.source || 'Source'"

2021-03-14 17:47 UTC, mikyjazz commented on config.example.js
> +                     id: "climate.000000000",
ok

2021-03-14 17:50 UTC, mikyjazz commented on scripts/controllers/main.js
> +         }
from my real configuration:
I can have Automatico instead of auto, and so on

                        states: {
                           'auto': 'Automatico',
                           'heat': 'Manuale',
                           'off': 'Spento'
                        },
                        icons: {
                           'auto': 'mdi-calendar-sync',
                           'heat': 'mdi-fire',
                           'off': 'mdi-power'
                        }

2021-03-14 17:53 UTC, mikyjazz commented on scripts/controllers/main.js
> +         }
![a](https://user-images.githubusercontent.com/38558161/111078589-8863df80-84f6-11eb-8d84-34de61e5c3cc.jpg)

2021-03-14 17:54 UTC, mikyjazz commented on scripts/controllers/main.js
> +         }
it assign the same value if definition is missing in states...

2021-03-14 17:54 UTC, mikyjazz commented on scripts/controllers/main.js
> +         }
to do reverselookup -> settingvalue

2021-03-14 17:56 UTC, mikyjazz commented on scripts/controllers/main.js
> +         }
the mechanism is the same with or without states definition...

2021-03-14 17:56 UTC, rchl commented on scripts/directives/tile.html
> +               <span ng-bind="(getWeatherField('windSpeed', item, entity) | number:0)"></span><!--
Don't understand what you mean.

I'm not talking about indentation change but about removal of `&nbsp;` which has a purpose there.

2021-03-14 17:58 UTC, rchl commented on scripts/controllers/main.js
> +         }
Ok, I get know that it has a meaning when user defines states.

2021-03-14 18:00 UTC, mikyjazz commented on scripts/directives/tile.html
> +               <span ng-bind="(getWeatherField('windSpeed', item, entity) | number:0)"></span><!--
changes in weather are "remaining" of previous changes/pull request; this features was ready at the same time of weather modifications; some changes not tracked/updated rrespect to your latest changes in other pr

2021-03-14 18:00 UTC, mikyjazz commented on scripts/directives/tile.html
> +               <span ng-bind="(getWeatherField('windSpeed', item, entity) | number:0)"></span><!--
sorry

2021-03-14 19:24 UTC, rchl commented on scripts/directives/tile.html
> +            <i class="item-climate--icon mdi" ng-class="entityIcon(item, entity)"></i>
sure but you are contributing to a project that cares...

I'll just set up an automatic formatter for HTML files then so we don't have to discuss such things in the future.

2021-03-14 19:24 UTC, rchl commented on scripts/directives/tile.html
> +                     <span ng-bind="entity.attributes.source || item.textSource || 'Source'"></span>
works for me

(we should document that new property also)

2021-03-14 19:29 UTC, rchl commented on scripts/directives/tile.html
> +                     <span ng-bind="entity.attributes.source || item.textSource || 'Source'"></span>
You did document it already. Sorry.

2021-03-14 19:29 UTC, rchl commented on scripts/directives/tile.html
>             ng-style="itemSelectStyles(entity, _options)">
The `_options` is an object now so `itemSelectStyles` won't work correctly now.

2021-03-14 19:37 UTC, rchl commented on scripts/controllers/main.js
> +   }
Here is my suggestion that reuses `item.states`, merging auto-discovered and user values together if the user did not include some. Also, this will make `item.states` the source of truth instead of creating a separate property for essentially the same thing.

```suggestion
   function initializeClimateStates (item, entity) {
      if (item.__statesExtended === undefined) {
         item.states = item.states || {};
         const options = item.useHvacMode ? entity.attributes.hvac_modes : entity.attributes.preset_modes;
         for (const option of options) {
            if (!(option in item.states)) {
               item.states[option] = option;
            }
         }
         item.__statesExtended = true;
      }
   }
```

Note that I've also renamed the function for clarity.

2021-03-14 19:41 UTC, rchl commented on scripts/controllers/main.js
> +   $scope.lookupClimateOption = function (item, entity, option) {
I'd suggest name `getClimateOptionText`

2021-03-14 19:41 UTC, rchl commented on scripts/controllers/main.js
> +   $scope.reverseLookupClimateOption = function (item, entity, option) {
I'd suggest the name `getClimateOptionFromText` and the last argument could be called `optionText` to differentiate from the `option` which typically refers to the state value.

2021-03-14 21:22 UTC, mikyjazz commented on scripts/controllers/main.js
> +   $scope.lookupClimateOption = function (item, entity, option) {
ok

2021-03-14 21:22 UTC, mikyjazz commented on scripts/controllers/main.js
> +   $scope.reverseLookupClimateOption = function (item, entity, option) {
ok

2021-03-14 21:26 UTC, mikyjazz commented on scripts/controllers/main.js
> +   }
item.__statesExtended are not only states, they can be also preset_modes that does not belong to entity state... it is an attribute

2021-03-14 21:26 UTC, mikyjazz commented on scripts/controllers/main.js
> +   }
so the correct name options...

2021-03-14 21:30 UTC, mikyjazz commented on scripts/directives/tile.html
>             ng-style="itemSelectStyles(entity, _options)">
itemSelectStyles checks only the existence of parameters, don't use at all

2021-03-14 21:30 UTC, mikyjazz commented on scripts/directives/tile.html
> +            <i class="item-climate--icon mdi" ng-class="entityIcon(item, entity)"></i>
:D

2021-03-14 22:26 UTC, rchl commented on scripts/directives/tile.html
>             ng-style="itemSelectStyles(entity, _options)">
It does set marginTop based on the number of items.

2021-03-14 22:30 UTC, rchl commented on scripts/controllers/main.js
> +   }
I feel like my suggested naming still works, even if the `preset_modes` are not really entity states. I mean if the user wants to localize `preset_modes` then he has to do that in `item.states` right? So from the user's perspective, it does appear to be "states" still.

(btw. the localization of states could be documented also since it's not entirely obvious how it works, especially with the `hvac_modes` and `preset_modes` being relevant here.

2021-03-29 20:04 UTC, akloeckner commented
I'm wondering: Isn't all that logic basically an exerpt of what `entityState` does? 
https://github.com/resoai/TileBoard/blob/4126d1a0e1dee9da5477a6ee03be9fd81bdae7e1/scripts/controllers/main.js#L525

If it is, can you make use of that (even more generic) function?

E.g.:
* `getClimateOptions` => something like mapping `hvacmodes` through `entityState`
* `getClimateCurrentOption` => just map current mode through `entityState`
* `setClimateOption` => that might be the hard case

2021-03-29 20:51 UTC, mikyjazz commented
> I'm wondering: Isn't all that logic basically an exerpt of what `entityState` does?
> https://github.com/resoai/TileBoard/blob/4126d1a0e1dee9da5477a6ee03be9fd81bdae7e1/scripts/controllers/main.js#L525
> 
> If it is, can you make use of that (even more generic) function?
> 
> E.g.:
> 
> * `getClimateOptions` => something like mapping `hvacmodes` through `entityState`
> * `getClimateCurrentOption` => just map current mode through `entityState`
> * `setClimateOption` => that might be the hard case

If you look closely at the code you will see that two different properties are mapped
  const option = item.useHvacMode? entity.state: entity.attributes.preset_mode;
I can't imagine how you would like to generalize this climate control specific thing ...

2021-04-22 10:34 UTC, rchl commented
@mikyjazz can you update us on what is the status of this on your side?

From my side, I think some of my comments are still unresolved.

2021-04-22 11:57 UTC, mikyjazz commented
hi Rafal,
some changes I have implemented in his time while the ones that are missing I have not taken into consideration; if you are interested in the pull request you can make them yourself. For my part, I realized that it is not possible to carry out a version for the public and one for me only so I have decided to carry out only my fork, with the changes I like, the style aspects that I like and without respecting (or at least without asking myself many problems about it) the constraints related to coding style; in the end it will be much easier to integrate in my version what you do in the master one;) See you soon.

2021-04-24 20:22 UTC, rchl commented
Merged manually to master. Thanks.

2021-04-24 20:22 UTC, closed without merging