Add Vertical Slider
resoai/TileBoard pull request #672
Opened 2021-03-22 01:39 UTC by timota

Add Vertical Slider tile.

Tile doesn't require any input from user, width and height will be calculated automatically based on Tile size. 
Best to use with tile `height` > 1. 
Also, some other options are available for user: `sliderHeight` and `sliderWidth`. If they are defined inside `slider` - they will be used in first place and take precedence via automated calculation. 
Also, Tile supports `icon`. If `icon` doesn't defined it will be taken to consideration in case of automatic calculation. 

Example:
```
{
    position: [0, 0],
    height: 3,
    id: 'light.entity',
    type: TYPES.SLIDER_VERTICAL,
    unit: '%',
    title: 'Slider',
    icon: 'mdi-lightbulb',
    state: false,
    filter: function (value) {
       var num = parseFloat(value) / 2.55 ;
       return num && !isNaN(num) ? num.toFixed() : 0;
    },
    value: '@attributes.brightness',
    slider: {
       max: 255,
       min: 0,
       step: 5,
       field: 'brightness',
       // sliderWidth: '60',
       // sliderHeight: '270',
       request: {
          type: "call_service",
          domain: "light",
          service: "turn_on",
          field: "brightness"
       },
    },
}
```

2021-03-22 21:42 UTC, rchl commented
Will also need to be added to TILES.md (example) and README.md (at least the new type)

2021-03-22 21:42 UTC, rchl requested changes

2021-03-22 21:42 UTC, rchl commented on scripts/controllers/main.js
> +      return styles;
Thanks for working on this. I have some comments.

Some issues I've observed:
 - the size calculation is not right. The check for icon doesn't work properly when `icon` property is not defined (you are only considering empty string)
![Screenshot 2021-03-22 at 22 25 12](https://user-images.githubusercontent.com/153197/112060445-7d93f500-8b5d-11eb-82aa-7d4657f62320.png)
 - the styling is not good with that particular theme (`CUSTOM_THEMES.HOMEKIT`). The text is not visible and the slider color blends with the background.
 - if I don't define the `height`, for example, it can end up looking like this:
![Screenshot 2021-03-22 at 22 30 23](https://user-images.githubusercontent.com/153197/112061105-483bd700-8b5e-11eb-8769-1f875a47553a.png)

2021-03-22 21:42 UTC, rchl commented on styles/main.less
> +   transform:rotate(270deg);
Please don't add prefixes for transforms. That can be done on building if not done already.

Also, sort all properties lexicographically.

2021-03-23 01:16 UTC, timota commented on styles/main.less
> +   transform:rotate(270deg);
This was fixed. Hope sorting correct.

2021-03-23 01:20 UTC, timota commented on scripts/controllers/main.js
> +      return styles;
2. Added styles for `CUSTOM_THEMES.HOMEKIT`. 
3. height has been fixed. 

1. Formula to count Slider Height is correct. Now i consider case when `item.icon is defined and empty`. 

Hope you will like these changes.

2021-03-23 01:22 UTC, timota commented on scripts/controllers/main.js
> +      const iconHeight = (item.icon && item.icon !== '') ? 0 : 42;
This will resolve issue when icon defined and empty.

2021-03-23 08:18 UTC, rchl requested changes

2021-03-23 08:18 UTC, rchl commented on scripts/controllers/main.js
> +      const iconHeight = (item.icon && item.icon !== '') ? 0 : 42;
The `item.icon` condition already covers the empty `item.icon` so just `item.icon` is equivalent to those two conditions.

Also, you are still not handling the case when `icon` is undefined (not set at all).

2021-03-23 08:18 UTC, rchl commented on scripts/controllers/main.js
> +      const sliderWidth = item.slider.sliderHeight || (itemWidth - tileSize * width + iconHeight - (height === 1 ? 0 : (20 + tileMargin)));
Still have the same problem I've mentioned with slider being rendered outside of the tile if height is not defined.

2021-03-23 08:18 UTC, rchl commented on scripts/directives/tile.html
> +         <div class="slidervertical-inner-icon" ng-if="item.icon && item.icon !==''">
Again, the `item.icon !==''` condition is redundant.

2021-03-23 08:18 UTC, rchl commented on styles/main.less
> +      border-top:20px solid @sliderColor;
Would appreciate having a space after `:` consistently.

2021-03-23 08:18 UTC, rchl commented on styles/themes.less
> +  }
I would hope there is some more generic way to do that that works in all themes because this is not very scalable.

I would expect to use some theme-specific color variables without repeating all those selectors in each theme.

Also, have you tested that it looks decent in every theme?

2021-03-23 08:18 UTC, rchl commented on styles/main.less
> +      box-shadow: -350px 0 0 350px @sliderColor, inset 0 0 0 80px @sliderThumbColor;
Those box-shadow offsets are rather large. Is that really correct / needed?

2021-03-23 08:18 UTC, rchl commented on scripts/controllers/main.js
> +      const itemWidth = tileSize * height + tileMargin * (height - 1);
For performance reasons, this should be cached. Otherwise Angular will run this code a lot.

You can use `cacheInItem` function to calculate this once since it doesn't seem like the result can change at runtime.

2021-03-23 09:47 UTC, timota commented on scripts/controllers/main.js
> +      const iconHeight = (item.icon && item.icon !== '') ? 0 : 42;
Logic here is that if icon defined set Height to 0, if not defined or empty set it to 42. In this case calculation a bit easier. Probably `iconHeight` is incorrect name for this value, as it works in reverse order.

2021-03-23 09:57 UTC, timota commented on scripts/controllers/main.js
> +      const sliderWidth = item.slider.sliderHeight || (itemWidth - tileSize * width + iconHeight - (height === 1 ? 0 : (20 + tileMargin)));
To be honest i don't have such issue. I've tested in in 2 browsers and both looks good and rendered correctly. 
in a code  `const height = item.height || 1;` which always will have result. 

Can you please shed more light on this?

2021-03-23 10:02 UTC, timota commented on scripts/directives/tile.html
> +         <div class="slidervertical-inner-icon" ng-if="item.icon && item.icon !==''">
got you. Removed.

2021-03-23 10:06 UTC, timota commented on styles/main.less
> +      border-top:20px solid @sliderColor;
got you. my fault

2021-03-23 10:11 UTC, rchl commented on scripts/controllers/main.js
> +      const sliderWidth = item.slider.sliderHeight || (itemWidth - tileSize * width + iconHeight - (height === 1 ? 0 : (20 + tileMargin)));
This is the tile I'm testing with:

```js
                  {
                     position: [0, 10],
                     width: 2, /*height: 4,*/
                     type: TYPES.SLIDER_VERTICAL,
                     title: 'SLIDER_VERTICAL',
                     unit: '%',
                     id: 'media_player.kitchen',
                     value: '@attributes.volume_level',
                     slider: {
                        max: 1,
                        min: 0,
                        step: 0.01,
                        request: {
                           type: 'call_service',
                           domain: 'media_player',
                           service: 'volume_set',
                           field: 'volume_level',
                        },
                        field: 'volume_level',
                     }
                  }
```

`TILE_SIZE` is 80 and `TILE_MARGIN` is 3. It looks a bit better when `width` is set to 1 but the slider still doesn't quite fit (even though it's positioned better).

2021-03-23 10:12 UTC, alphasixtyfive commented
I'm sorry to interrupt you guys, but here are my two thoughts:

1) This should probably be called `VERTICAL_SLIDER` rather than `SLIDER_VERTICAL`
2) I would think that default theme should not have rounded corners of the slider to better match the overall boxy style yet Homekit theme would be great with it.

2021-03-23 10:13 UTC, rchl commented on scripts/controllers/main.js
> +      const iconHeight = (item.icon && item.icon !== '') ? 0 : 42;
Improving the variable name would definitively help with readability.

2021-03-23 10:38 UTC, timota commented on scripts/controllers/main.js
> +      const sliderWidth = item.slider.sliderHeight || (itemWidth - tileSize * width + iconHeight - (height === 1 ? 0 : (20 + tileMargin)));
i'll take a look.

2021-03-24 23:46 UTC, timota commented on scripts/controllers/main.js
> +      const itemWidth = tileSize * height + tileMargin * (height - 1);
These props have been added to cache.

2021-03-24 23:47 UTC, timota commented on styles/main.less
> +      box-shadow: -350px 0 0 350px @sliderColor, inset 0 0 0 80px @sliderThumbColor;
Unfortunately it required. Without it styles are broken

2021-03-24 23:53 UTC, timota commented on scripts/controllers/main.js
> +      const sliderWidth = item.slider.sliderHeight || (itemWidth - tileSize * width + iconHeight - (height === 1 ? 0 : (20 + tileMargin)));
To make it work i have changed a calculation logic a bit. Here an explanation.

```js
      // defines free space used by icon
      const iconSpacer = item.icon ? 0 : 35;

      // if `item.slider.sliderHeight` is defined - set SIZE(height or width) to custom value
      // if `item.slider.sliderHeight` is not defined: make calculation and compare if it greater than (0/20) accordingly .
      // This prevents:
      //    to show very small sliders (less than 20px in this case, probably can be increased)
      //    negative values, which can break alignment
      // If user would like to override automatic calculation appropriate option has to be defined
      const sliderWidth = item.slider.sliderWidth || (x => x > 0 ? x : 0)(itemWidth - 30);
      const sliderHeight = item.slider.sliderHeight || (x => x > 20 ? x : 0)(itemHeight - 100 + iconSpacer);
```

With this - your example works. But didnt test it on tileSize < 80, as i believe, in this case, user has to define custom `sliderHeight/sliderWidth` to make it look nice.

2021-03-24 23:55 UTC, timota commented on scripts/controllers/main.js
> +      const iconHeight = (item.icon && item.icon !== '') ? 0 : 42;
Value was renamed, explanation below.
```js
      // defines free space used by icon
      const iconSpacer = item.icon ? 0 : 35;
```

Hope this makes sense.

2021-03-25 00:42 UTC, timota commented on styles/themes.less
> +  }
> I would hope there is some more generic way to do that that works in all themes because this is not very scalable.
I would expect to use some theme-specific color variables without repeating all those selectors in each theme.

This can be changed to use parameterised `mixin`s. 

```less
#lib-range-holder-input() {
  .range-holder-input() {
    generic_attr: attr;
    
    &::-webkit-slider-runnable-track {
      color: @Value1; 
    }
    &::-moz-range-track {
      color: @Value2;
    }
  }
}

@Value1: green;
@Value2: red;

.range-holder input[type="range"] {
    #lib-range-holder-input.range-holder-input();
}

.-theme-homekit {
  
  @Value1: black;
  @Value2: white;
  
  .range-holder input[type="range"] {
    extend_attr: extend;
    #lib-range-holder-input.range-holder-input();
    
    &::-moz-range-track {
      extend_this: this;
    }
  }
}

```

Result:
```css
.range-holder input[type="range"] {
  generic_attr: attr;
}
.range-holder input[type="range"]::-webkit-slider-runnable-track {
  color: green;
}
.range-holder input[type="range"]::-moz-range-track {
  color: red;
}
.-theme-homekit .range-holder input[type="range"] {
  extend_attr: extend;
  generic_attr: attr;
}
.-theme-homekit .range-holder input[type="range"]::-webkit-slider-runnable-track {
  color: black;
}
.-theme-homekit .range-holder input[type="range"]::-moz-range-track {
  color: white;
}
.-theme-homekit .range-holder input[type="range"]::-moz-range-track {
  extend_this: this;
}
```
In this case you can get rid of all those selectors and manage all with variables, but potentially raw css will grow in size as all basic attrs can be populated inside themes selectors. Have to be careful with this.

Another way use parameterised mixins as functions;
```less
#lib-range-holder-input() {
  .range-input(@Val1, @Val2) {
    color: @Val1;
    background: @Val2;
  }
}

@Val1: green;
@Val2: red;

.range-holder input[type="range"] {
  &::-webkit-slider-runnable-track {
    #lib-range-holder-input.range-input(@Val1, @Val2);
  } 
}

.-theme-homekit {
  
  @Value1: black;
  @Value2: white;
  
  .range-holder input[type="range"] {
    &::-webkit-slider-runnable-track {
      #lib-range-holder-input.range-input(@Value1, @Value2);
    }
  }
}
```

result:
```css
.range-holder input[type="range"]::-webkit-slider-runnable-track {
  color: green;
  background: red;
}
.-theme-homekit .range-holder input[type="range"]::-webkit-slider-runnable-track {
  color: black;
  background: white;
}
```
In this case we have to define selectors inside themes as well, but code looks more clear/readable as for me. 

So please choose which you prefer.

2021-03-25 00:50 UTC, timota commented
@alphasixtyfive 
1. to be honest i like `VERTICAL_SLIDER` more than `SLIDER_VERTICAL`.  I named it `slider_vertical` as this points to the same tile `family` - slider. If all parties are ok to rename - im ok with this. 

> default theme should not have rounded corners

for me it looks so cubic. at least, probably  `radius:2px` ?

2021-03-25 19:49 UTC, rchl requested changes
I've actually come to the realization that I'd like this functionality to be merged into `SLIDER`. It could just have a flag to switch to horizontal mode. Otherwise, everything becomes inconsistent as SLIDER has a generic name but can only be horizontal, and also the styles for both of those are completely different. I think the styles for `SLIDER` don't really work that well for Tileboard as the slider is very small so it would make sense to consolidate that.

I can help with doing that work.

2021-03-25 19:49 UTC, rchl commented on TILE_EXAMPLES.md
> +    height: 2,    // Best works with height > 1. In case height=1, better use custom sliderHeight to achieve your needs
I'm not sure why talking about explicit values like "1". Doesn't everything depend on tile `tileSize` also?

"1" could mean 80 pixels for some but 240 for others.

2021-03-25 19:49 UTC, rchl commented on scripts/controllers/main.js
> +      const width = cacheInItem(item, 'width', () => item.width || 1);
I meant to cache the whole result.

Let me just push the change so that we don't spend too much time doing back-and-forth.

2021-03-25 20:13 UTC, timota commented on TILE_EXAMPLES.md
> +    height: 2,    // Best works with height > 1. In case height=1, better use custom sliderHeight to achieve your needs
Merge tiles is really good idea. I will try to make my best to make it happened. 
Your help more than welcome - many thanks.

2021-03-25 20:17 UTC, timota commented on TILE_EXAMPLES.md
> +    height: 2,    // Best works with height > 1. In case height=1, better use custom sliderHeight to achieve your needs
And that description has been wrote before i changed the way how size calculated. We can change it last when all features will be implemented. Thanks

2021-03-25 20:18 UTC, rchl commented on TILE_EXAMPLES.md
> +    height: 2,    // Best works with height > 1. In case height=1, better use custom sliderHeight to achieve your needs
I've pushed some changes to kickstart that.

I'm testing with those 3 tiles:

```js
                  {
                     position: [8, 8],
                     height: 2, width: 2,
                     id: 'media_player.kitchen',
                     value: '@attributes.volume_level',
                     type: TYPES.SLIDER,
                     title: 'SLIDER (legacy)',
                     // subtitle: 'SLIDER (legacy)',
                     legacy: true,
                     // state: false,
                     // bottom: true, // puts slider on bottom
                     slider: {
                        max: 1,
                        min: 0,
                        step: 0.01,
                        request: {
                           type: 'call_service',
                           domain: 'media_player',
                           service: 'volume_set',
                           field: 'volume_level',
                        },
                        field: 'volume_level',
                     },
                  },
                  {
                     position: [10, 8],
                     width: 2, height: 2,
                     type: TYPES.SLIDER,
                     title: 'SLIDER (new, horizontal)',
                     vertical: true,
                     unit: '%',
                     icon: 'mdi-lightbulb',
                     id: 'light.hallway',
                     value: '@attributes.brightness',
                     filter: function (value) {
                        // Since light brightness range is typically from 0-256,
                        // this filter converts the value to 0-100.
                        var num = parseFloat(value) / 2.55 ;
                        return num && !isNaN(num) ? num.toFixed() : 0;
                     },
                     slider: {
                        max: 255,
                        min: 0,
                        step: 5,
                        field: 'brightness',
                        request: {
                           type: "call_service",
                           domain: "light",
                           service: "turn_on",
                           field: "brightness"
                        },
                     }
                  },
                  {
                     position: [12, 8],
                     width: 2, height: 2,
                     type: TYPES.SLIDER,
                     title: 'SLIDER (new, vertical)',
                     vertical: true,
                     unit: '%',
                     icon: 'mdi-lightbulb',
                     id: 'light.hallway',
                     value: '@attributes.brightness',
                     filter: function (value) {
                        // Since light brightness range is typically from 0-256,
                        // this filter converts the value to 0-100.
                        var num = parseFloat(value) / 2.55 ;
                        return num && !isNaN(num) ? num.toFixed() : 0;
                     },
```

2021-04-08 19:49 UTC, timota commented
Sorry for a long delay in work, was busy with family/work issues. 

So, This commit contains Vertical and Horizontal sliders. 
Vertical behaves same way as it was before (you can manage width/height on your own or leave it for auto-calculation)

New options:
```
  vertical: true,
  alignRow: false,
```

For Horizontal i have added new option to make Tile look `column` or 'row' aligned:
 - Column looks in similar to old(legacy) one, with some re-arrangements (icon added) and slider positioned horizontally. 
 - Row on other side, re arrange items inside Tile to look in-line started with icon, slider and value. (more on screenshots)

To make it testing easier, below you can find Tiles examples. 

```js
                  {
                     position: [0, 0],
                     width: 2, height: 2,
                     type: TYPES.SLIDER,
                     title: 'SLIDER (vertical 1)',
                     vertical: true,
                     alignRow: false,
                     unit: '%',
                     icon: 'mdi-lightbulb',
                     id: 'light.f1_r2_light_tv_wall',
                     value: '@attributes.brightness',
                     slider: {
                        max: 255,
                        min: 0,
                        step: 5,
                        field: 'brightness',
                        // sliderHeight: 50,
                        // sliderWidth: 80,
                        request: {
                           type: "call_service",
                           domain: "light",
                           service: "turn_on",
                           field: "brightness"
                        },
                     }
                  },
                  {
                     position: [2, 0],
                     width: 2, height: 1,
                     type: TYPES.SLIDER,
                     title: 'SLIDER (vertical 2)',
                     vertical: true,
                     alignRow: true,
                     unit: '%',
                     icon: 'mdi-lightbulb',
                     id: 'light.f1_r2_light_tv_wall',
                     value: '@attributes.brightness',
                     slider: {
                        max: 255,
                        min: 0,
                        step: 5,
                        field: 'brightness',
                        // sliderHeight: 30,
                        // sliderWidth: 80,
                        request: {
                           type: "call_service",
                           domain: "light",
                           service: "turn_on",
                           field: "brightness"
                        },
                     }
                  },
                  {
                     position: [2, 1],
                     width: 1, height: 1,
                     type: TYPES.SLIDER,
                     title: 'SLIDER (vertical 2)',
                     vertical: true,
                     alignRow: true,
                     unit: '%',
                     icon: '',
                     id: 'light.f1_r2_light_tv_wall',
                     value: '@attributes.brightness',
                     slider: {
                        max: 255,
                        min: 0,
                        step: 5,
                        field: 'brightness',
                        // sliderHeight: 30,
                        // sliderWidth: 80,
                        request: {
                           type: "call_service",
                           domain: "light",
                           service: "turn_on",
                           field: "brightness"
                        },
                     }
                  },
                  {
                     position: [4, 0],
                     width: 1, height: 2,
                     type: TYPES.SLIDER,
                     title: 'SLIDER (vertical 3)',
                     vertical: true,
                     // alignRow: true,
                     unit: '%',
                     icon: 'mdi-lightbulb',
                     id: 'light.f1_r2_light_tv_wall',
                     value: '@attributes.brightness',
                     slider: {
                        max: 255,
                        min: 0,
                        step: 5,
                        field: 'brightness',
                        // sliderHeight: 120,
                        // sliderWidth: 80,
                        request: {
                           type: "call_service",
                           domain: "light",
                           service: "turn_on",
                           field: "brightness"
                        },
                     }
                  },
                  {
                     position: [5, 0],
                     width: 0.5, height: 2,
                     type: TYPES.SLIDER,
                     title: 'SLIDER (vertical 4)',
                     vertical: true,
                     alignRow: true,
                     state: '',
                     unit: '%',
                     icon: 'mdi-lightbulb',
                     id: 'light.f1_r2_light_tv_wall',
                     value: '@attributes.brightness',
                     slider: {
                        max: 255,
                        min: 0,
                        step: 5,
                        field: 'brightness',
                        // sliderHeight: 120,
                        // sliderWidth: 80,
                        request: {
                           type: "call_service",
                           domain: "light",
                           service: "turn_on",
                           field: "brightness"
                        },
                     }
                  },
                  {
                     position: [0, 2],
                     width: 2, height: 2,
                     type: TYPES.SLIDER,
                     title: 'SLIDER (horiz/col)',
                     vertical: false,
                     alignRow: false,
                     unit: '%',
                     icon: 'mdi-lightbulb',
                     id: 'light.f1_r2_light_tv_wall',
                     value: '@attributes.brightness',
                     slider: {
                        max: 255,
                        min: 0,
                        step: 5,
                        field: 'brightness',
                        // sliderHeight: 120,
                        // sliderWidth: 80,
                        request: {
                           type: "call_service",
                           domain: "light",
                           service: "turn_on",
                           field: "brightness"
                        },
                     }
                  },
                  {
                     position: [2, 2],
                     width: 2, height: 1,
                     type: TYPES.SLIDER,
                     title: 'SLIDER (horiz/col)',
                     vertical: false,
                     alignRow: false,
                     unit: '%',
                     icon: 'mdi-lightbulb',
                     id: 'light.f1_r2_light_tv_wall',
                     value: '@attributes.brightness',
                     slider: {
                        max: 255,
                        min: 0,
                        step: 5,
                        field: 'brightness',
                        // sliderHeight: 120,
                        // sliderWidth: 80,
                        request: {
                           type: "call_service",
                           domain: "light",
                           service: "turn_on",
                           field: "brightness"
                        },
                     }
                  },
                  {
                     position: [2, 3],
                     width: 1, height: 1,
                     type: TYPES.SLIDER,
                     title: 'SLIDER (horiz/col)',
             [...]

2021-04-08 20:50 UTC, alphasixtyfive commented
Thanks for great work but I really think that the default theme should stay without rounded corners to keep the style consistent.

2021-04-08 21:11 UTC, timota commented
> Thanks for great work but I really think that the default theme should stay without rounded corners to keep the style consistent.

default theme has only `radius 2px` just to smooth edges. On screenshot `homekit` theme.

2021-04-09 20:57 UTC, rchl commented
It will take me a while to review this properly so please be patient. :)

Just was quickly checking for now and noticed that it doesn't work that well with smaller tiles (tileSize 80):

![Screenshot 2021-04-09 at 22 55 48](https://user-images.githubusercontent.com/153197/114239845-e3b6af80-9986-11eb-9c37-4b9c63657a93.png)

2021-04-09 21:00 UTC, rchl commented
Actually bigger tile size doesn't really help. It appears it's more about the colors of the input. I think you need to override more of its styles since it's probably picking OS styles (macOS/chrome here).

![Screenshot 2021-04-09 at 22 59 59](https://user-images.githubusercontent.com/153197/114240138-558ef900-9987-11eb-8d07-7b110705e594.png)

2021-04-09 21:05 UTC, rchl commented
Is the `alignRow` option really needed? It looks rather cramped in the row configuration. And there is a lot of unused space in the tile. What would be the use case for that?

2021-04-09 21:10 UTC, rchl commented
Quick update. Looks saner when the slider is not at max value but still not good enough. Not enough contrast to be able to tell where the slider control is.

![Screenshot 2021-04-09 at 23 09 15](https://user-images.githubusercontent.com/153197/114240909-9d625000-9988-11eb-9084-2ea39a604bc6.png)

2021-04-09 21:13 UTC, timota commented
> It will take me a while to review this properly so please be patient. :)
> 
> Just was quickly checking for now and noticed that it doesn't work that well with smaller tiles (tileSize 80):
> 
> ![Screenshot 2021-04-09 at 22 55 48](https://user-images.githubusercontent.com/153197/114239845-e3b6af80-9986-11eb-9c37-4b9c63657a93.png)

i will take a look what i can do

2021-04-09 21:15 UTC, timota commented
> Actually bigger tile size doesn't really help. It appears it's more about the colors of the input. I think you need to override more of its styles since it's probably picking OS styles (macOS/chrome here).
> 
> ![Screenshot 2021-04-09 at 22 59 59](https://user-images.githubusercontent.com/153197/114240138-558ef900-9987-11eb-8d07-7b110705e594.png)

Thats really strange. i'm using mac/catalina/chrome and dont have access to WinOS at all. If you can help me to identify colours for that it will be great.

2021-04-09 21:17 UTC, timota commented
> Quick update. Looks saner when the slider is not at max value but still not good enough. Not enough contrast to be able to tell where the slider control is.
> 
> ![Screenshot 2021-04-09 at 23 09 15](https://user-images.githubusercontent.com/153197/114240909-9d625000-9988-11eb-9084-2ea39a604bc6.png)

same as previous comment - for me colours look nice. I can make them a bit darker to look better. I will try android tablet to and hope i can find golden middle.

2021-04-09 21:18 UTC, rchl commented
> Thats really strange. i'm using mac/catalina/chrome and dont have access to WinOS at all. If you can help me to identify colours for that it will be great.

I'm on macOS also, not Windows. I'm on Big Sur though, which can make a difference.

2021-04-09 21:18 UTC, timota commented
> Is the `alignRow` option really needed? It looks rather cramped in the row configuration. And there is a lot of unused space in the tile. What would be the use case for that?
> 
> EDIT: But maybe the "cramped" issue is just a matter of adding some more padding. I guess it could be useful for creating tiles that take little space vertically...

 I can be wrong but as for me slider `horizontal/AlignRow` as it should looks like.

2021-04-09 21:26 UTC, timota commented on scripts/globals/constants.js
> +   SLIDER_VERTICAL: 'slider_vertical',
need to remove this as it not required any more

2021-04-09 21:39 UTC, timota commented
> > Thats really strange. i'm using mac/catalina/chrome and dont have access to WinOS at all. If you can help me to identify colours for that it will be great.
> 
> I'm on macOS also, not Windows. I'm on Big Sur though, which can make a difference.

can you be so kind and pickup colours that work well on Big Sur ? i can compare them with colours on Catalina and Android.
Thanks

2021-04-09 21:45 UTC, rchl reviewed
> can you be so kind and pickup colours that work well on Big Sur ? i can compare them with colours on Catalina and Android.
> Thanks

Actually, I see now what's happening. Your entity is in "off" state so its background is a bit transparent, making the slider stand out. Turn that entity on and you will see the same as me.

2021-04-09 21:45 UTC, rchl commented on styles/main.less
> +// }
Remove all commented-out code if it's not needed.

2021-04-09 21:56 UTC, rchl commented
I haven't checked all themes but it seems to look decent with `border: 1px solid #808080;`

![Screenshot 2021-04-09 at 23 55 35](https://user-images.githubusercontent.com/153197/114244644-22e8fe80-998f-11eb-9efd-018a273dee8d.png)

2021-04-14 11:55 UTC, timota reviewed
these are done

2021-04-14 11:55 UTC, timota commented on scripts/globals/constants.js
> +   SLIDER_VERTICAL: 'slider_vertical',
done in upcoming commit

2021-04-14 11:55 UTC, timota commented on styles/main.less
> +// }
done in upcoming commit

2021-04-14 12:09 UTC, timota commented
So... in the latest commit i have rearrange styles a bit to fit into lowest possible(without modification) `tileSize: 90px`.
If `tileSize < 90` - some inputs from user are required:
  - `icon` has to be removed to fit it nicely
  - `state` can be disabled as for me it doesnt make any sense as we have `value`

Below you can find screenshots:

`tileSize: 90px`
<img width="981" alt="Screenshot 2021-04-14 at 13 02 56" src="https://user-images.githubusercontent.com/11276397/114707122-bf115d80-9d21-11eb-991e-045ba0b8c428.png">

`tileSize: 80px` default view. Some tiles are marked `FIXME`
<img width="885" alt="Screenshot 2021-04-14 at 13 05 14" src="https://user-images.githubusercontent.com/11276397/114707386-11527e80-9d22-11eb-9928-08792a2618e1.png">

`tileSize: 80px` user modified (removed: icon, state)
<img width="899" alt="Screenshot 2021-04-14 at 13 08 23" src="https://user-images.githubusercontent.com/11276397/114707757-802fd780-9d22-11eb-876d-9df0e5c4f8a0.png">

Hopefully all these make sense.

2021-04-19 09:11 UTC, timota commented
@rchl sorry for bothering, but did you have a chance to review this PR ?

2021-04-19 10:32 UTC, rchl commented
Didn't have much time. Will try in the evening.

2021-04-19 19:11 UTC, rchl commented
I'll be fixing those as I comment as I don't want to prolong this but just mentioning here so you are up to date.

In the default theme, the text color should be white (to match existing tiles and make the contrast better):

![Screenshot 2021-04-19 at 21 09 06](https://user-images.githubusercontent.com/153197/115290190-917a4900-a153-11eb-8eb5-7914e2c85a66.png)

2021-04-19 19:27 UTC, rchl commented on TILE_EXAMPLES.md
> +    },
A lot needs to be made up to date here. Also update screenshot to use the default theme, for consistency.

2021-04-19 19:58 UTC, rchl commented on scripts/directives/tile.html
> +            <span ng-if="(_unit = entityUnit(item, entity))" ng-bind="_unit"></span>
Existing classes need to be reused (with some overrides) instead of creating a completely new one as that is a recipe for creating inconsistencies with existing themes.

2021-04-19 21:49 UTC, rchl commented
OK, I did some updates that I wanted. Feel free to try it out and check if I did break something, before merging.

2021-04-20 09:37 UTC, timota reviewed
Except one comment regarding custom slider height - all looks good

2021-04-20 09:43 UTC, rchl commented on scripts/controllers/main.js
> +            }
My thinking was that if the input is not visible then it should not have a layout since then it would be focusable. That said, focusing stuff with the keyboard is probably not something very relevant in TileBoard so it's more a theoretical issue. But OK, will revert that.

2021-04-20 09:56 UTC, timota reviewed
thanks

2021-04-20 10:03 UTC, merged

2021-04-20 10:03 UTC, rchl commented
Thanks for your work on this!