Docker
resoai/TileBoard pull request #793
Opened 2021-11-17 13:59 UTC by chetan

Hi,

I noticed there's no official docker build for the project. The below is a simple build which serves using `nginx:alpine`. If you'd like to set up an official repository, let me know and I can update the repository name in the readme below.

chetan

2021-11-17 14:22 UTC, rchl commented
> If you'd like to set up an official repository, let me know and I can update the repository name in the readme below.

I'm OK with having an official docker image for this project but then I'd expect the docker images to be made automatically from CI. Similar to how it's done from the `tileboard-addon` repo - https://github.com/resoai/TileBoard-addon/blob/b6a67d80c82edb634503110b31de91ed6e1bbb79/.github/workflows/on_tag.yaml#L22-L22

2021-11-17 19:48 UTC, chetan commented
@rchl added the workflow step for building and pushing the docker image. Have not tested all the way through, but it should work.

2021-11-19 13:03 UTC, rchl requested changes

2021-11-19 13:03 UTC, rchl commented on .github/workflows/on_push.yaml
> +      - name: Login to DockerHub
I think I would prefer to have images created only for tagged releases (from `on-tag.yaml`).

2021-11-19 15:14 UTC, chetan commented on docker/Dockerfile
> +FROM node:latest AS builder
This image is only used for building and the larger image is usually safer in case anything needs to be compiled for one of the various dependencies in the chain. Pinning to a version is a good idea though.

2021-11-19 15:17 UTC, chetan commented on .github/workflows/on_push.yaml
> +      - name: Login to DockerHub
Could have a `:latest` (or `:git`) docker tag that tracks the main branch in addition to the specific tags. Totally up to you, though.

2021-11-20 11:59 UTC, rchl commented on .github/workflows/on_push.yaml
> +            -t tileboard/tileboard:master \
Since we are building tagged releases now, `latest` tag is more appropriate. `master` would be built from every commit.

2021-11-22 20:09 UTC, rchl approved these changes

2021-11-22 20:09 UTC, merged

2021-11-22 20:09 UTC, rchl commented
Thanks.